document.write("<script src='defconf.js'></script>")
document.write("<script src='xhr.js'></script>")
document.write("<script src='model.js'></script>")
document.write("<script src='core.js'></script>")
document.write("<script src='source.js'></script>")
document.write("<script src='index.js'></script>")
document.write("<script src='paneles.js'></script>")
