#!/bin/env bash


# Verified base paths
# Directorios base  de la distribución original OSIRIS-OZONE (o2on3)

V_def_release_base="/var/osiris2"
V_def_BIO_base="/o2iris"




echo "Get Verified Code"
echo "Make Pub Key"
