#!/usr/bin/bash

set -e

#if [ -f /usr/bin/osiris000 ]; then
#  echo "El archivo /usr/bin/osiris000 ya existe. Ignorándolo."
#fi


echo "Post Install File"







        if [ -f /tmp/osiris2_install_vars ]; then
        
        echo " Leyendo Mensaje Preinstall ... "
            VARIABLE_RECIBIDA=$(cat /tmp/osiris2_install_vars)
            if [[ $VARIABLE_RECIBIDA == "EXEC" ]]; then
            
            echo "Entrando en osiris"
            echo $pwd   
            cd bin
            ./osiris
            fi
            
            rm /tmp/osiris2_install_vars
        else
            echo "No se encontró el archivo temporal."
        fi













echo "END OF INSTALLER"


exit 0



